export const genre: {
    name: string;
    originalName: string;
}[] = [
    { name: "Шодзо", originalName: "Shoujo" },
    { name: "Дзосей", originalName: "Josei" },
    { name: "Шонен", originalName: "Shounen" },
    { name: "Сейнен", originalName: "Seinen" },
    { name: "Апокалипсис", originalName: "Apocalyptic" },
    { name: "Безумство", originalName: "Madness" },
    { name: "Биопанк", originalName: "Biopunk" },
    { name: "Экшн", originalName: "Action" },
    { name: "Боевые искусства", originalName: "Martial Arts" },
    { name: "Вампиры", originalName: "Vampires" },
    { name: "Военное", originalName: "Military" },
    { name: "Гарем", originalName: "Harem" },
    { name: "Демоны", originalName: "Demons" },
    { name: "Детектив", originalName: "Detective" },
    { name: "Добутсу (Животное)", originalName: "Dobutsu (Animal)" },
    { name: "Драма", originalName: "Drama" },
    { name: "Игры", originalName: "Games" },
    { name: "Идолы", originalName: "Idols" },
    { name: "Икебукуро", originalName: "Ikebukuro" },
    { name: "Исекай", originalName: "Isekai" },
    { name: "Историческое", originalName: "Historical" },
    { name: "Кайто (Тайна)", originalName: "Kaito (Mystery)" },
    { name: "Киберпанк", originalName: "Cyberpunk" },
    { name: "Комедия", originalName: "Comedy" },
    { name: "Космическая опера", originalName: "Space Opera" },
    { name: "Космос", originalName: "Space" },
    { name: "Магия", originalName: "Magic" },
    {
        name: "Махо Шоджо (Волшебница)",
        originalName: "Mahou Shoujo (Magical Girl)",
    },
    { name: "Машины", originalName: "Machines" },
    { name: "Меха", originalName: "Mecha" },
    { name: "Мистика", originalName: "Mystery" },
    { name: "Моэ", originalName: "Moe" },
    { name: "Музыка", originalName: "Music" },
    { name: "Мыльная опера", originalName: "Soap Opera" },
    { name: "Отаку", originalName: "Otaku" },
    { name: "Парапсихология", originalName: "Parapsychology" },
    { name: "Пародия", originalName: "Parody" },
    { name: "Стимпанк", originalName: "Steampunk" },
    { name: "Повседневная жизнь", originalName: "Everyday Life" },
    { name: "Полицейский экшн", originalName: "Police Action" },
    { name: "Полицейский", originalName: "Police" },
    { name: "Постапокалиптика", originalName: "Post-apocalyptic" },
    { name: "Приключения", originalName: "Adventure" },
    { name: "Психология", originalName: "Psychological" },
    { name: "Психологический триллер", originalName: "Psychological Thriller" },
    { name: "Реверсивный гарем", originalName: "Reverse Harem" },
    { name: "Романтика", originalName: "Romance" },
    { name: "Самурай", originalName: "Samurai" },
    {
        name: "Самурайский экшн (Таямбара)",
        originalName: "Samurai Action (Tayambara)",
    },
    { name: "Сверхъестественное", originalName: "Supernatural" },
    { name: "Сёдзё-ай", originalName: "Shoujo-ai" },
    { name: "Сёнэн-ай", originalName: "Shounen-ai" },
    { name: "Сказка", originalName: "Fairy Tale" },
    { name: "Спорт (Спокон)", originalName: "Spokon (Sports)" },
    { name: "Сентай", originalName: "Sentai" },
    { name: "Токусацу", originalName: "Tokusatsu" },
    { name: "Триллер", originalName: "Thriller" },
    { name: "Ужасы", originalName: "Horror" },
    { name: "Научная фантастика", originalName: "Science Fiction" },
    { name: "Фэнтези", originalName: "Fantasy" },
    { name: "Школа", originalName: "School" },
    { name: "Школьный детектив", originalName: "School Detective" },
    { name: "Экшн", originalName: "Action" },
];
