export const ROUTES = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    CATALOG: "/catalog",
    LIBRARY: "/library",
    SPONSOR_PROJECT: "/sponsor-project",
    HELP: "/help",
    PROFILE: "/profile",
    SEASON: "/season",
    TRAILER: "/trailer",
    SETTINGS: "/settings",
    FAQ: "/faq",
    CONTACTS: "/contacts",
    ADVERTISMENT: "/advertisment",
    USER_AGREEMENT: "/user-agreement",
    PRIVACY_POLICY: "/privacy-policy",
    COMPLAINT: "/complaint",
    TITLE: "/title/:titleId",
};
